services:
  entrytracker_app:
    build: .
    environment:
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=app_db
    depends_on:
      - mysql_db
    networks:
      - app_network

  mysql_db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=app_db
    volumes:
      - mysql_ci_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - entrytracker_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_ci_data:
